#!/bin/bash

# Configuration
BASE_URL="http://localhost:8080"
USER_ID="demo_user_$(date +%s)"

# Colors for pretty printing
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}=== Cymbal Sports Mock API Demo ===${NC}"
echo "Target URL: $BASE_URL"
echo "Simulated User ID: $USER_ID"
echo "-----------------------------------"

# Helper function to pause
pause() {
    echo -e "${GREEN}Press ENTER to continue...${NC}"
    read
    echo ""
}

# Helper function to run a curl command
run_api_call() {
    DESCRIPTION=$1
    METHOD=$2
    ENDPOINT=$3
    DATA=$4

    echo -e "${BLUE}Step: $DESCRIPTION${NC}"
    echo "Request: $METHOD $ENDPOINT"
    
    if [ "$METHOD" == "POST" ]; then
        echo "Payload: $DATA"
        response=$(curl -s -X POST "$BASE_URL$ENDPOINT" \
            -H "Content-Type: application/json" \
            -d "$DATA")
    else
        response=$(curl -s -X GET "$BASE_URL$ENDPOINT")
    fi

    # Try to pretty print with jq if installed, otherwise just print
    if command -v jq &> /dev/null; then
        echo "$response" | jq .
    else
        echo "$response"
    fi
    
    pause
}

# 1. Check API Status
run_api_call "Check API Health" "GET" "/api/"

# 2. Save Inventory (One-time setup)
run_api_call "Initialize Inventory (ETL Process)" "GET" "/api/save_inventory"

# 3. Get All Categories
run_api_call "Fetch Product Categories" "GET" "/api/products/categories"

# 4. Get Top Products
run_api_call "Fetch Top Selling Products" "GET" "/api/products/top"

# 5. Get Products by Category
# We'll assume 'Running' exists from our generator script
run_api_call "Fetch Products in 'Running' Category" "GET" "/api/products/category/Running"

# 6. Search for Products
run_api_call "Search for 'Gloves'" "GET" "/api/products/search?q=Gloves"
run_api_call "Search for 'Balls'" "GET" "/api/products/search?q=Balls"

# 7. Get Product Details (Simulate picking a specific SKU)
# We'll use a hardcoded SKU that we know exists from the generator script (SKU-10001 is usually the first generated)
# But to be safe let's assume one specific fake one or just use one. 
# Better: Let's pick SKU-10001 which is generated by the script loop starting at 10000+0
run_api_call "Fetch Details for Item SKU-10001" "GET" "/api/products/SKU-10001"

# 7. Add Item to Cart
run_api_call "Add SKU-10001 to Cart (Qty: 2)" "POST" "/api/cart/add" \
    "{\"user_id\": \"$USER_ID\", \"item_id\": \"SKU-10001\", \"quantity\": 2}"

# 8. Add Another Item
run_api_call "Add SKU-10005 to Cart (Qty: 1)" "POST" "/api/cart/add" \
    "{\"user_id\": \"$USER_ID\", \"item_id\": \"SKU-10005\", \"quantity\": 1}"

# 9. Get Cart Details
run_api_call "Get Full Cart Details" "GET" "/api/cart/$USER_ID"

# 10. Remove Item
# 9. Remove Item
run_api_call "Remove SKU-10001 from Cart" "POST" "/api/cart/remove" \
    "{\"user_id\": \"$USER_ID\", \"item_id\": \"SKU-10001\"}"

# 11. Check Order Status (Mock)
run_api_call "Check Order Status (Mock Order ID)" "GET" "/api/orders/ORDER-999"

# 12. Return Mock Order
run_api_call "Return Order" "POST" "/api/orders/ORDER-999/return" \
    "{\"order_id\": \"ORDER-999\", \"reason\": \"Wrong size\"}"

# 13. Create User Account
run_api_call "Create User Account" "POST" "/api/users" \
    "{\"username\": \"$USER_ID\", \"password\": \"password123\"}"

# 14. Login
run_api_call "Login User" "POST" "/api/login" \
    "{\"username\": \"$USER_ID\", \"password\": \"password123\"}"

echo -e "${BLUE}=== Demo Complete ===${NC}"
